"""
Django settings for socodri project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+d5q4whgp&tya*(&fc!l!@98e6m$thw@^5_zm*f0ej&-!b$c3s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django_extensions',
    'socodri',
    'restless'
)

MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'socodri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'socodri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/socodri/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
SOCIALCODE_LOGIN_PATH = "/"
SOCIALCODE_LOGOUT_PATH = "/logout"
SOCIALCODE_BASE_URL = 'https://app.socialcode.com'
CURRENT_USER_API = '/api/bouncer/v2/user/current/'
AUDIENCE_LINKAGE_API = '/api/audiences/v1/facebooklinkage/'
FB_APP_ID = 'none'
FB_APP_SECRET = 'of your'
FB_ACCESS_TOKEN = 'business'

USE_MOCKS = True
# mocks
MOCK_USER = {
    'id': 99,
    'is_staff': True,
    'image_url': 'https://ssl.gstatic.com/accounts/ui/avatar_2x.png',
    'email': 'mock@socialcodeinc.com',
    'first_name': 'Mock',
    'last_name': 'User'
}
